# Generated by Django 2.2.5 on 2019-11-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STekstovi',
            new_name='Tekstovi',
        ),
    ]
