# Generated by Django 2.2.5 on 2019-11-24 22:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovaObjava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=220)),
                ('datum', models.DateField()),
                ('slika', models.FileField(blank=True, null=True, upload_to='')),
                ('tekst', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Novi Objava',
            },
        ),
    ]
