# Generated by Django 2.2.5 on 2019-11-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novaobjava',
            options={'verbose_name_plural': 'Nova Objava'},
        ),
    ]
